server:
  servlet:
    session:
      persistent: true
      timeout: 7200000
  port: 8082

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://192.168.1.200:3306/db_test?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: qwerASDF1234?
      url: jdbc:mysql://127.0.0.1:3306/db_office-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 0
      max-active: 20
      min-idle: 1
      max-wait: 60000
      filter:
        stat:
          enabled: true
          type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true

  # create 第一次建表用create，后面使用update
  # update 没有表创建，只有更新
  # 不然每次重新系统工程都会先删除表再新建
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  cache:
    type: redis
  #redis
  redis:
    host: 192.168.1.200
    port: 6379

#thymeleaf
#开发时关闭缓存,不然没法看到实时页面
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  #配置文件上传的最大值
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  #热部署指定端口,具体视自己情况而定,只要不重复就可以
  devtools:
    # 禁止自动重启
    restart:
      enabled: false
    livereload:
      port: 35730

#dubbo
dubbo:
  application:
    name: office-cloud-dubbo-start
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    threads: 10
    threadpool: fixed
    loadbalance: roundrobin

#cat日志
app:
  logdir: /Users/apple_22/Desktop/logdir/office-cloud
  cat:
    enabled: false
